notifications:
  email: false

sudo: required

language: node_js

node_js:
  - node

services:
  - docker

before_install:
- docker build -t dador/javascriptsubtitlesoctopus .

script:
- docker run --rm -v ${PWD}:/code dador/javascriptsubtitlesoctopus:latest